# R-E P. Miller
# CS: Information Technology
# CSC 328_010
# Fall 2023
# Assignment #6 - Sockets (Server)
# Makefile
# Created 10/31/23
# Due @ 11pm 11/07/23

all: server

server:
	cp p6.py server
	chmod u+x server

clean:
	rm -f server *.o *~

.PHONY: submit

submit:
	~schwesin/bin/submit csc328 project6
