# R-E P. Miller
# CS: Information Technology
# CSC 328_010
# Fall 2023
# Assignment #4
# Makefile
# Created 9/28/23
# Due @ 11pm 10/5/23

all: project4

project4:
	cp p4.py project4
	chmod u+x project4

clean:
	rm -f project4 *.o *~

.PHONY: submit

submit:
	~schwesin/bin/submit csc328 project4
